# Generated by Django 5.2.7 on 2025-10-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoritedMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.BigIntegerField()),
                ("movie_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favorited_movies",
                "indexes": [
                    models.Index(
                        fields=["account_id"], name="favorited_m_account_cdf321_idx"
                    ),
                    models.Index(
                        fields=["movie_id"], name="favorited_m_movie_i_a0c0da_idx"
                    ),
                ],
                "unique_together": {("account_id", "movie_id")},
            },
        ),
    ]
