# Generated by Django 5.2.7 on 2025-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritedmovie",
            name="genre_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="favoritedmovie",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="favoritedmovie",
            name="poster_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="favoritedmovie",
            name="release_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="favoritedmovie",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="favoritedmovie",
            name="vote_average",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="FavoritedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.BigIntegerField()),
                ("list_name", models.CharField(max_length=255)),
                ("movie_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favorite_lists",
                "indexes": [
                    models.Index(
                        fields=["account_id"], name="favorite_li_account_054f48_idx"
                    )
                ],
            },
        ),
    ]
