# Generated by Django 5.2.7 on 2025-10-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0002_favoritedmovie_genre_ids_favoritedmovie_overview_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favoritedlist",
            new_name="favorited_l_account_68cef5_idx",
            old_name="favorite_li_account_054f48_idx",
        ),
        migrations.AlterModelTable(
            name="favoritedlist",
            table="favorited_lists",
        ),
    ]
