# Generated by Django 5.2.7 on 2025-10-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "favorites",
            "0003_rename_favorite_li_account_054f48_idx_favorited_l_account_68cef5_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoritedlist",
            name="movie_ids",
        ),
    ]
