# Generated by Django 5.2.7 on 2025-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favorites", "0004_remove_favoritedlist_movie_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritedlist",
            name="list_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
